name: Generate Pacman Game

on:
  schedule:
    - cron: "0 */2 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # خطوة الـ Commit اليومي عشان تضمن المربعات الخضراء تزيد
      - name: Update activity file
        run: |
          echo "Last Activity: $(date)" > activity.txt
          git config --global user.name "Sherif Ashraf"
          git config --global user.email "sherifashraf51203@gmail.com"
          git add activity.txt
          git commit -m "activity update" || echo "No changes"
          git push origin main

      # توليد لعبة باكمان (تأكد من كتابة اسم اليوزر صح)
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: sherif-ashraf512
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # رفع الصورة لفرع output
      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
